"use client";
import {questions} from "@/data/questions";
import {readiness} from "@/lib/readiness";
import type {AppState} from "@/lib/types";
import {exportState,importState,resetState} from "@/lib/storage";
import SyncPanel from "./SyncPanel";

export default function ProgressView({state,update}:{state:AppState;update:(s:AppState)=>void}) {
  const seen=questions.filter(q=>state.questionStates[q.id]?.attempts).length;
  const mastered=questions.filter(q=>state.questionStates[q.id]?.status==='mastered').length;
  const weak=questions.filter(q=>state.questionStates[q.id]?.status==='weak').length;
  const r=readiness(state,questions);
  const avg=state.mockHistory.length?Math.round(state.mockHistory.reduce((n,m)=>n+m.score,0)/state.mockHistory.length*10)/10:0;
  const download=async()=>{const blob=new Blob([await exportState()],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ccse-desk-export.json';a.click();URL.revokeObjectURL(a.href)};
  const importFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{update(await importState(await file.text()))}catch(err){alert(err instanceof Error?err.message:'Invalid export')}};
  return <section className="py-7"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--tint)]">Progress</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><h2 className="text-4xl font-bold tracking-tight">Know your runway.</h2><span className={`rounded-full px-4 py-2 text-xs font-semibold uppercase ${r.ready?'bg-[var(--success)] text-white':'bg-[var(--label)] text-[var(--surface)]'}`}>{r.ready?'Ready':'Not ready yet'}</span></div><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Seen',`${seen}/300`],['Mastered',mastered],['Weak',weak],['Mock avg',avg||'—']].map(([l,v])=><div key={l} className="rounded-2xl border border-[var(--separator)] bg-[var(--surface)] p-4 shadow-sm"><p className="text-xs uppercase tracking-widest text-[var(--secondary)]">{l}</p><strong className="mt-2 block text-3xl tabular-nums">{v}</strong></div>)}</div><div className="mt-8 rounded-2xl border border-[var(--separator)] bg-[var(--surface)] p-5 shadow-sm sm:p-6"><h3 className="text-[13px] font-semibold uppercase tracking-widest">Readiness criteria</h3><div className="mt-4 grid gap-3">{r.conditions.map(c=><div key={c.label} className="flex items-center gap-3 border-t border-[var(--separator)] pt-3"><span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs ${c.met?'bg-[var(--success)] text-white':'bg-[var(--surface-2)] text-[var(--secondary)]'}`}>{c.met?'✓':'·'}</span><div><p className="font-semibold">{c.label}</p><p className="text-xs text-[var(--secondary)]">{c.detail}</p></div></div>)}</div></div><div className="mt-8"><h3 className="text-[13px] font-semibold uppercase tracking-widest">Mock history</h3>{state.mockHistory.length?<div className="mt-3 grid gap-2">{state.mockHistory.slice(0,8).map(m=><div key={m.id} className="flex justify-between border-b border-[var(--separator)] py-3 text-sm"><span>{new Date(m.timestamp).toLocaleDateString('es-ES')}</span><b className="tabular-nums">{m.score}/25</b></div>)}</div>:<p className="mt-3 text-[var(--secondary)]">Your mock history will appear here.</p>}</div><SyncPanel state={state} update={update}/><div className="mt-8 flex flex-wrap gap-3"><button onClick={download} className="focus-ring min-h-11 rounded-xl border border-[var(--separator)] px-4 py-3 text-xs font-semibold uppercase tracking-wider">Export state</button><label className="focus-ring min-h-11 cursor-pointer rounded-xl border border-[var(--separator)] px-4 py-3 text-xs font-semibold uppercase tracking-wider">Import state<input type="file" accept="application/json" onChange={importFile} className="hidden"/></label><button onClick={async()=>{if(confirm('Reset all local study state? This cannot be undone.')){await resetState();location.reload()}}} className="focus-ring min-h-11 rounded-xl border border-[var(--danger)] px-4 py-3 text-xs font-semibold uppercase tracking-wider text-[var(--danger)]">Reset</button></div></section>;
}
